# This is a basic workflow to help you get started with Actions

name: Publish Docker image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  # Use the branches filter when you need to filter branches for positive matches and exclude branches
    branches: [ docker-demo, docs-demo ] # Assume docker-demo = feature & docs-demo = develop branch
  # Use the branches-ignore filter when you only need to exclude branch names
  #  branches-ignore: [ master ]
  
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  
  job1:
    name: Get Current branch name
    outputs:
      extract_branch: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - name: Current Branch
        id: extract_branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF##*/})"
  
  job2:
  needs: job1
  name: Build and push docker image 
     
  steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/demo-image-repo:${{ needs.job1.outputs.extract_branch }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}