# This is a basic workflow to help you get started with Actions

name: Publish Docker image

on:
  push:
  # Use the branches filter when you need to filter branches for positive matches and exclude branches
    branches: [ docker-demo, docs-demo ] # Assume docker-demo = feature & docs-demo = develop branch
  # Use the branches-ignore filter when you only need to exclude branch names
  #  branches-ignore: [ master ]
  
  pull_request:
    branches: [ master ]

jobs:

  job1:
    runs-on: ubuntu-latest
    name: Get Current branch name
    outputs:
      extract_branch: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - name: Current Branch
        id: extract_branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF##*/})"
  
  job2:
    runs-on: ubuntu-latest
    needs: job1
    name: Build and push docker image 
    
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/demo-image-repo:${{ needs.job1.outputs.extract_branch }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}